CREATE TABLE ads (
  ad_id serial not null primary key,
  list_id int,
  orig_list_time timestamp,
  list_time timestamp,
  status varchar(100),
  type varchar(100),
  name varchar(250),
  phone int,
  region int,
  city int,
  category int,
  user_id int,
  passwd varchar(300),
  phone_hidden boolean,
  no_salesmen boolean,
  company_ad boolean,
  subject varchar(500),
  body text,
  price numeric(15, 2),
  old_price numeric(15, 2),
  image varchar(500),
  infopage varchar(500),
  infopage_title varchar(500),
  store_id int,
  salted_password varchar(500),
  modified_at timestamp,
  adtype varchar(100)
);